### ISSUE TITLE
include subpackages in __init__.py files

### ISSUE THREAD

**Issue by jairideout** [biocore/scikit-bio#1309]
Importing a module should have its sub-modules/packages available. For example, the following paths should be accessible:

```python
import skbio
skbio.stats.ordination
skbio.diversity
...
```

These examples currently fail with an `AttributeError`.

To fix this, sub-modules/packages need to be imported in the package's `__init_.py` and added to `__all__`.

See #1258 and #1307 for original discussion.

**Comment by jolespin** [comment]
Is this fixed on the current stable version? If not, is there a way around it atm? 

```
$ conda install -c https://conda.anaconda.org/biocore scikit-bio
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/jespinoz/anaconda:
#
scikit-bio                0.4.2               np112py36_0    bioconda
jespinozlt-osx:pt_I jespinoz$ python
Python 3.6.1 |Anaconda custom (x86_64)| (default, Mar 22 2017, 19:25:17)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from skbio import stats
>>> stats.ordination
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'skbio.stats' has no attribute 'ordination'
```

**Comment by jairideout** [comment]
The fix is available in scikit-bio 0.5.1 (it was merged after 0.5.0 release went out).

**Comment by jolespin** [comment]
`conda install -c https://conda.anaconda.org/biocore scikit-bio` installed 0.4.2.  Is there a way to directly install 0.5.1 via conda or pip?

**Comment by jairideout** [comment]
scikit-bio 0.5.0 and later are only compatible with Python 3. Is your conda environment using Python 2?

**Comment by jolespin** [comment]
I'm using Python 3.6.1 but I think it might be an issue with PyQT5 because my ete3 and ScikitBio broke at the same time when I updated some other modules.

**Comment by jairideout** [comment]
Can you try creating a new environment with the latest version of scikit-bio? I tested this locally and I get Python 3.5.3 and scikit-bio 0.5.1 (that's the latest release):

```shell
conda create -n scikit-bio -c https://conda.anaconda.org/biocore scikit-bio
```

**Comment by jolespin** [comment]
Yup it worked.  I think it has something to do with my PyQT.  I wonder how I can get skbio and ete3 to work with Python 3.6 b/c it was working not too long ago until I updated a bunch of packages.  I'm not sure which one generated the confusion.

**Comment by jairideout** [comment]
Glad to hear it worked! Perhaps you could try installing ete3 in this new environment you created?

**Comment by jolespin** [comment]
That was the plan but I have a pretty elaborate .ipython startup file that has all of my boiler plate/helper functions.  Many of them use the f"{x}" string formatting exclusive to Python 3.6.  Do you know of any ways to reconfigure my current environment to set a priority on ScikitBio and ete3 when updating the other packages?

**Comment by jairideout** [comment]
I don't, sorry. Perhaps check with the `conda` support team?

**Comment by mortonjt** [comment]
To install ete with skbio, you need pyqt==4.11.4

I'm not sure about python=3.6, but I'm definitely able to install with
python=3.5

**Comment by jolespin** [comment]
Fixed it!  Skbio is working with 3.6.1

**Comment by jolespin** [comment]
I found the culprit btw.  I was going to update my pandas and it wants to downgrade scikitbio.  I brought up an issue on conda.  Do you have any insight on this? 

https://github.com/conda/conda/issues/5732
