### ISSUE TITLE
BUG: Strange behavior in Treenode prune / shear / bifurcate

### ISSUE THREAD

**Issue by mortonjt** [biocore/scikit-bio#1416]
When I run the following commands
```python
In [1]: from skbio import TreeNode

In [2]: tree = TreeNode.read([u'(((a,b,f,g),c),d);'])

In [3]: new_tree = tree.shear(['a','b','c','f'])

In [4]: new_tree.bifurcate()

In [5]: new_tree.prune()

In [6]: [n.name for n in new_tree.tips()]
```
I get this error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-21abf6988dfb> in <module>()
----> 1 [n.name for n in new_tree.tips()]

<ipython-input-24-21abf6988dfb> in <listcomp>(.0)
----> 1 [n.name for n in new_tree.tips()]

/Users/mortonjt/Documents/UCSD/research/scikit-bio/skbio/tree/_tree.py in tips(self, include_self)
   1315 
   1316         """
-> 1317         for n in self.postorder(include_self=False):
   1318             if n.is_tip():
   1319                 yield n

/Users/mortonjt/Documents/UCSD/research/scikit-bio/skbio/tree/_tree.py in postorder(self, include_self)
   1151                     break
   1152                 curr = curr.parent
-> 1153                 curr_children = curr.children
   1154                 curr_children_len = len(curr_children)
   1155                 child_index_stack.pop()

AttributeError: 'NoneType' object has no attribute 'children'
```

Note that this only occurs with scikit-bio==0.5.0.  Any idea what is going on?

**Comment by jairideout** [comment]
@wasade would you be able to look into this?

**Comment by wasade** [comment]
I'll get a fix in tomorrow. I think I know what's up

**Comment by wasade** [comment]
For added notes on the bug, it can be recreated just by the `shear` call (i.e., no need for `bifurcate` or `prune`). The source of the problem is a violation of the tree structure as a the child of a parent does not point back to the same parent:

What we expect:

```python
In [25]: id(tree.children[0].parent)
Out[25]: 4563406976

In [26]: id(tree)
Out[26]: 4563406976
```

What we observe:

```python
In [27]: id(new_tree.children[0].parent)
Out[27]: 4563722984

In [28]: id(new_tree)
Out[28]: 4563723376
```

**Comment by wasade** [comment]
This bug was introduced in #1398. The specific line in the relevant commit is [here](https://github.com/biocore/scikit-bio/commit/b21d1632855fd6a7e601610d36c04721a100ff1d#diff-ed8f191ff5b76128cc77196aae792868R411) where a call to `self.children.extend` was performed instead of a call to `self.extend`. The difference being that `self.children.extend` is a `list.extend`, without knowledge of `TreeNode` whereas `TreeNode.extend` performs an update if necessary to the `parent` pointer.

**Comment by wasade** [comment]
@jairideout @mortonjt ready for review

**Comment by ebolyen** [comment]
Fixed by #1417

**Comment by jairideout** [comment]
Thanks for the fix @wasade!
